apiVersion: v1
kind: Service
metadata:
  name: oas-validator-service
  namespace: istio-system
spec:
  ports:
  - name: grpc-auth
    port: 9000
    targetPort: 9000
  selector:
    istio: ingressgateway # Points to the gateway pod where the container lives